spring:
  data:
    mongodb:
      host: localhost
      username: user-app
      password: temporal
      port: 27017
      database: apirest
    rest:
      base-path: /api
  jackson:
    property-naming-strategy: SNAKE_CASE